function opts=assembly_default_options(rootDir,varargin)
if nargin<1||isempty(rootDir), rootDir=pwd; end
opts=struct('rootDir',rootDir,'dataRoot','/home/blanche/data', ...
 'processedRoot',fullfile(rootDir,'data_processed','assemblies'), ...
 'figureRoot',fullfile(rootDir,'outputs','assemblies'), ...
 'qcFile',fullfile(rootDir,'QC_ENTRY_KEPT_files.csv'), ...
 'morphs',{{'surface','molino','pachon'}},'analysisDurationMin',30, ...
 'pcaField','deltaFoF','activityField','raster','residualField','', ...
 'analysisLabel','raw_candidates','cellSelectionMode','candidates', ...
 'nNullIter',200,'nullPercentile',95,'nullEigenvalueMode','parallelAnalysis', ...
 'minShiftFraction',.10,'promaxPower',4,'loadingThreshold',1.75, ...
 'minAssemblySize',2,'mergeSimilarAssemblies',true,'similarityThreshold',.60, ...
 'pruneWeakAssemblies',true,'pruneNullIterations',200,'pruneSyncBinFrames',3, ...
 'pruneMinSyncFraction',2/3,'randomSeed',1,'overwriteExisting',false, ...
 'maxSessionsPerMorph',Inf,'makeFigures',true,'runTag','batch', ...
 'screenNullIter',200,'finalNullIter',1000,'matchNullIter',200, ...
 'gridMinSize',12,'gridMaxSize',16,'smokeMode',false);
if mod(numel(varargin),2), error('Options must be name/value pairs.'); end
for k=1:2:numel(varargin), n=varargin{k}; if ~isfield(opts,n), error('Unknown option: %s',n); end, opts.(n)=varargin{k+1}; end
assert(strcmpi(opts.cellSelectionMode,'candidates'),'Only candidate HD cells are supported.');
assert(isempty(regexp(opts.analysisLabel,'[^A-Za-z0-9_-]','once')),'Unsafe analysisLabel.');
end
