function options=assembly_activation_defaults()
%ASSEMBLY_ACTIVATION_DEFAULTS Shared activation defaults for comparison scripts.
options=struct('minActiveMembers',2,'onRecruitmentFraction',0.5, ...
 'offRecruitmentFraction',0.5,'minMatchingIndex',0.50, ...
 'activationNullAlpha',0.05,'nNullShuffles',1000, ...
 'minDurationSeconds',0.50,'minNullShiftSeconds',10.0,'randomSeed',1);
end